### ISSUE TITLE
Discontinuity in waveforms in newly tensorized Bedmaster hd5 files

### ISSUE THREAD

**Issue by erikr** [aguirre-lab/ml4c3#1258] opened 2021-01-28 01:35 UTC
## Error message or warning
![image](https://user-images.githubusercontent.com/1253422/106077076-d48dc880-60de-11eb-865c-9e2a61007120.png)
`x axis` is sample number.
`y axis` is timestamp.

Check MGH email for the MRN and CSN.

## Expected behavior
No discontinuity.

## Possible solution
Fix bug in tensorization pipeline.

## Steps to reproduce
```
t = hd5["bedmaster/$CSN/waveform/i/time"][()]
plt.plot(t)
```

**Comment by erikr** [comment] 2021-01-28 01:36
@RidwanAlam @StevenSong Please edit body of original issue above to make the problem clearer. I also suggest you CC @matt-cdac @contactadityag on the email, since they have access to our `ml4c3` directory on `mad3` and also are doing some signal QC work.

**Comment by erikr** [comment] 2021-01-28 14:08
> @raimonpv: we might want to create a script that checks that there is no time discontinuity for all the given files. So we can run a quick check after tensorization

Good idea. I think we can use `explore` and just need to write a `TensorMap` that checks for discontinuities.

Also, question for rest of @aguirre-lab/ml4c3-dev: is it time to make a simple QC pipeline? It could be modular so we can start with just the above `check_discontinuities`, and over time add to it.

@epalto @RidwanAlam have the most need, since their projects use Bedmaster data. What do you both think?

**Comment by RidwanAlam** [comment] 2021-01-28 14:52
I am not sure at this point. Will running a script like that after tensorization fix the issue? How do we fix the issue? Ignoring that mrn is not a fix/solution, I think. Also, I would like to know what @matt-cdac and @contactadityag think on this issue. Is the issue coming from the .mat files, or even before, or a later part in the pipeline?

**Comment by erikr** [comment] 2021-01-28 14:57
Good question, and I agree ignoring the file does not solve the problem. I think it is reasonable to do two parallel activities:
1. Quantify the problem, e.g. of X Bedmaster `hd5` files, how many have a discontinuity in one or more signals? Which signals does this problem occur in?
2. Determine the root cause; is this problem in the `.mat` source? Or do we introduce it in our pipeline?

Note how task 1 informs task 2.

**Comment by StevenSong** [comment] 2021-01-28 14:59
I'm working on debugging (step 2 outlined above)

**Comment by erikr** [comment] 2021-01-28 15:01
Thanks Steven!

@RidwanAlam do you have bandwidth to focus on step 1 above?

**Comment by RidwanAlam** [comment] 2021-01-28 15:01
Yes, I will tomorrow onward. Thanks.

**Comment by RogerPallares** [comment] 2021-01-28 16:41
@StevenSong I don't know if you already checked it, but it doesn't seem to be a problem of the CrossReferencer class when it sorts Bedmaster files:

https://github.com/aguirre-lab/ml4c3/blob/74cdb5491c77d573cf8ccf76e02251d896f92b1f/ingest/icu/readers.py#L1660-L1664

I checked the output and BM files are properly sorted in the output dictionary.

**Comment by StevenSong** [comment] 2021-01-28 16:44
yes, I also checked this and agreed, the list is sorted correctly

**Comment by RogerPallares** [comment] 2021-01-28 16:51
Also, considering the time when the discontinuity happens, I'm pretty sure the issue is in the files `WHT08_818-1588276668_<#bunlde>_v4.mat`, so they may be faulty or the interbundle correction is not done properly?

**Comment by erikr** [comment] 2021-01-28 16:54
If the error is in interbundle correction, we should notify @wolfgang-ganglberger @matt-cdac @contactadityag so they can fix.

In the meanwhile, we will wait for @RidwanAlam to complete step 1 above. That info will be useful for the CDAC team. We can also proceed with our work on "good" files once we determine which are free of this discontinuity.

**Comment by StevenSong** [comment] 2021-01-28 16:56
I thought the discontinuity was around `'/media/lm4-bedmaster/BLK08_854-1586853541_0_v4.mat'` actually, the timestamp of the discontinuity is `1586853541`

**Comment by RogerPallares** [comment] 2021-01-28 17:02
I see, so then it looks like `BLK08_854-1586853541_<#bunlde>_v4.mat` is put before `WHT08_818-1588276668_<#bunlde>_v4.mat` when writing bedmaster data

**Comment by matt-cdac** [comment] 2021-01-28 17:05
What exactly is the discontinuity? I see the plot referring to sample number but I don't totally understand the visual. Is the issue that we're missing data for a certain range of time?

**Comment by StevenSong** [comment] 2021-01-28 17:08
i have more plots and can follow up in a second

**Comment by StevenSong** [comment] 2021-01-28 17:17
@matt-cdac the discontinuity is that between `.mat` files, the time the signals were recorded should be monotonically increasing (or after correction, close enough to increasing)

what the plot is showing is a jump back in time of 21 days, where the y-axis of the plot is the timestamp and the x-axis is the index of the measurement within a concatenated array of measurements across `.mat` files

@RogerPallares and I have traced this back to 2 `.mat` files, `LUN06_620-1586396113_38_v4.mat and BLK08_854-1586853541_0_v4.mat`. If we isolate the timestamps from these files for the same signal (ECG lead I) and plot them similar to above, we see the exact discontinuity that was propogated to our `.hd5` files:
![image](https://user-images.githubusercontent.com/26208374/106173868-67237b80-6162-11eb-985e-990dc2b9bb65.png)

based on our understanding of the structure of the `.mat` files, `BLK08_854-1586853541_0_v4.mat` should start entirely after `LUN06_620-1586396113_38_v4.mat`

**Comment by StevenSong** [comment] 2021-01-28 17:23
> @matt-cdac the discontinuity is that between `.mat` files, the time the signals recorded should be monotonically increasing (or after correction, close enough to increasing) but they arent
> 
> what the plot is showing is a jump back in time of 21 days, where the y-axis of the plot is the timestamp and the x-axis is the index of the measurement within a concatenated array of measurements across `.mat` files
> 
> @RogerPallares and I have traced this back to 2 `.mat` files, `LUN06_620-1586396113_38_v4.mat and BLK08_854-1586853541_0_v4.mat`. If we isolate the timestamps from these files for the same signal (ECG lead I) and plot them similar to above, we see the exact discontinuity that was propogated to our `.hd5` files:
> ![image](https://user-images.githubusercontent.com/26208374/106173868-67237b80-6162-11eb-985e-990dc2b9bb65.png)
> 
> based on our understanding of the structure of the `.mat` files, `BLK08_854-1586853541_0_v4.mat` should start entirely after `LUN06_620-1586396113_38_v4.mat`
> 
> > Is the issue that we're missing data for a certain range of time?
> 
> note that jumps forward in time are entirely okay, the patient was being moved and disconnected for a while, but the issue is that there are jumps back in time
> 
> additionally, the plot seems to suggest the patient was in 2 places at once, as they have signals from both LUN06 and BLK08 that share the same timestamps. @epalto, when bundles overlap like this, what was the strategy before? should we check that bundles do not overlap across departments?

**Comment by matt-cdac** [comment] 2021-01-28 17:23
I see, thanks @StevenSong this is very helpful!

**Comment by RogerPallares** [comment] 2021-01-28 17:33
Okay, this is really really weird. First of all I checked if this could be a problem of the matching algorithm. For what I checked it doesn't seem so if we consider our ADT as ground truth: The ADT we are using it only has this patient in which the file `LUN06_620-1586396113_38_v4.mat`  falls within the patient's Transfer in and Transfer out of LUN06. Then, if we compare `LUN06_620-1586396113_38_v4.mat` initial time with ADT, it seems correct, it's like 3 hours after the patient enters to the bed in LUN06. However, this patient is transferred out but the `LUN06_620-1586396113_38_v4.mat` finishes much after. Then I have two thoughts:
1. Our ADT is not accurate enough and we have patients missing so another could match this file (`LUN06_620-1586396113_38_v4.mat`). I don't think this is the case though, because it would also mean that 2 patients would be at the same bed at the same time.
2. Somebody in the hospital forgot to turn down the monitors and the next patient that was monitored was recorded with the same file, so some bundles are from one patient, other bundles from another.

**Comment by epalto** [comment] 2021-01-28 17:42
>  @epalto, when bundles overlap like this, what was the strategy before? should we check that bundles do not overlap across departments?

Bundles on `.mat` files have overlapping information from their previous bundle. During tensorization we remove those overlapped fragments on the interbundle correction. However, if there was an error with that and the overlapped fragments were not removed, we would have identical values for the repeated timestamps, which is not the case on the signal above, so I don't think the interbundle correction is a problem

**Comment by StevenSong** [comment] 2021-01-28 17:46
@RogerPallares that's a really good find, actually looking closer at the full plot of the discontinuity, it looks like there's at the timestamp of the jump back in time, it looks like there's also a jump forward in time from the signal from LUN06- here's the same plot as before but with a vertical line highlighting the timestamp of the discontinuity and a red circle on where the jump forward during LUN06 is:
![discontinuity](https://user-images.githubusercontent.com/26208374/106177613-bcfa2280-6166-11eb-899d-d91dc7f25813.png)

could this be that this patient actually left LUN06 and the signal is actually from new patient?

**Comment by raimonpv** [comment] 2021-01-28 17:50
> Somebody in the hospital forgot to turn down the monitors and the next patient that was monitored was recorded with the same file, so some bundles are from one patient, other bundles from another.

I'll go for something like that. As far as  I remember Yuping told us that there might be files that correspond to more than one patient.

**Comment by raimonpv** [comment] 2021-01-28 17:52
How does the signals look after the patient left LUN06? are empty or there is recording there? the same applied to the file associated to BLK8.

> edit: pure speculation but the timestamp is from 4/14/2020, during the first covid peak, maybe this reflects some of the chaos the hospital faced during that time where admissions were not precisely tracked or the typical records we use to construct our ADT are not perfectly clean

By assessing when and how many patients present this irregularity we could answer your hypothesis

**Comment by RidwanAlam** [comment] 2021-01-28 17:56
> @RogerPallares and I have traced this back to 2 `.mat` files, `LUN06_620-1586396113_38_v4.mat and BLK08_854-1586853541_0_v4.mat`. If we isolate the timestamps from these files for the same signal (ECG lead I) and plot them similar to above, we see the exact discontinuity that was propogated to our `.hd5` files:
> ![image](https://user-images.githubusercontent.com/26208374/106173868-67237b80-6162-11eb-985e-990dc2b9bb65.png)
> 
> based on our understanding of the structure of the `.mat` files, `BLK08_854-1586853541_0_v4.mat` should start entirely after `LUN06_620-1586396113_38_v4.mat`

The start times in the filenames of these files are different, aren't they?

**Comment by RogerPallares** [comment] 2021-01-28 17:56
> could this be that this patient actually left LUN06 and the signal is actually from new patient?

Yes I would think so. As you remark this could reflect this situation and two patients were recorded on the same file. This is thinking ahead, but in order to avoid this problem we should consider compare the Bedmaster signals we write to `hd5` to the TransferOut in ADT, then we could cut the signal when the patient is transferred to another bed.

**Comment by raimonpv** [comment] 2021-01-28 18:02
> Yes I would think so. As you remark this could reflect this situation and two patients were recorded on the same file. This is thinking ahead, but in order to avoid this problem we should consider compare the Bedmaster signals we write to hd5 to the TransferOut in ADT, then we could cut the signal when the patient is transferred to another bed.

If you plot the actual value of any signal does it make sense? I mean, after the patient was transferred out from LUN06, the signals saved make sense?

**Comment by RidwanAlam** [comment] 2021-01-28 18:05
As far as I understood, the .mat files have no patient information, not even what's the start bundle or end bundle, right? Why is the assumption that consequent bundles belong to same patient? Why should it?

**Comment by RidwanAlam** [comment] 2021-01-28 18:06
> As far as I understood, the .mat files have no patient information, not even what's the start bundle or end bundle, right? Why is the assumption that consequent bundles belong to same patient? Why should it?

Or even the same .mat file can have different patients' data, right?

**Comment by RidwanAlam** [comment] 2021-01-28 18:07
When I sort the time array, there is no big jump forward

**Comment by StevenSong** [comment] 2021-01-28 18:08
> > based on our understanding of the structure of the `.mat` files, `BLK08_854-1586853541_0_v4.mat` should start entirely after `LUN06_620-1586396113_38_v4.mat`
> 
> The start times in the filenames of these files are different, aren't they?

right but perhaps my statement isn't entirely correct, looking purely at start time isn't enough, like @RogerPallares suggested, we should look at the timestamps of the signals and compare them to the ADT and cutoff signals after they are transferred out of a department

> As far as I understood, the .mat files have no patient information, not even what's the start bundle or end bundle, right? Why is the assumption that consequent bundles belong to same patient? Why should it?

I think it's because the `.mat` files in a bundle actually come from a single `.stp` file - so typically, a new `.stp` file is generated when the monitor is turned on?

> When I sort the time array, there is no big jump forward

I think this is expected as there are overlapping timestamps but looking at the plot, there's a tiny little jump forward ![discontinuity](https://user-images.githubusercontent.com/26208374/106177613-bcfa2280-6166-11eb-899d-d91dc7f25813.png)

**Comment by RogerPallares** [comment] 2021-01-28 18:09
> I think it's because the `.mat` files in a bundle actually come from a single `.stp` file - so typically, a new `.stp` file is generated when the monitor is turned on for each patient but sometimes maybe the monitor is left on and it continues writing to the same file?
This is what I also understood.

**Comment by erikr** [comment] 2021-01-28 18:16
> I think it's because the .mat files in a bundle actually come from a single `.stp` file - so typically, a new `.stp` file is generated when the monitor is turned on for each patient but sometimes maybe the monitor is left on and it continues writing to the same file?

I recall @wolfgang-ganglberger and Yuping said the above is possible, and that we cannot assume 1:1 patient:`.stp` file.

**Comment by RidwanAlam** [comment] 2021-01-28 18:19
> > I think it's because the .mat files in a bundle actually come from a single `.stp` file - so typically, a new `.stp` file is generated when the monitor is turned on for each patient but sometimes maybe the monitor is left on and it continues writing to the same file?
> 
> I recall @wolfgang-ganglberger and Yuping said the above is possible, and that we cannot assume 1:1 patient:`.stp` file.

I am not sure who, most likely Aaron, mentioned that it's possible the monitor being left on across patients. As @erikr pointed, we can't that 1;1 correspondence. Are the xref files generated with that assumption?

**Comment by StevenSong** [comment] 2021-01-28 18:20
> Are the xref files generated with that assumption?

yes but that's why @RogerPallares suggested we check the transfer times when we cross reference as well

**Comment by contactadityag** [comment] 2021-01-28 18:21
@erikr, This is correct there is no guarantee that only one patient is associated with one .stp file. Multiple Patients can be associated with a single .stp file. This is why Patient Matching is done to correctly associate which part of .stp corresponds to which patient. I think @matt-cdac can probably explain this in more detail.

**Comment by RogerPallares** [comment] 2021-01-28 18:25
For now we only checked transfer in times, as it is as easy as compare the file name with the ADT TransferIn column. However if we encounter that this issue happens usually, we should also compare the TransferOut column with the last time stamp in a bedmaster signal. This would be much more time consuming, since we would have to open files and compare timestamps, but it would allow to avoid these kind of discontinuities.

**Comment by StevenSong** [comment] 2021-01-28 18:26
can we change the `.mat` conversion process to instead save the start and end time of each bundle? that way, if a bundle overlaps a transfer in/out time, we only have to open that 1 `.mat` file which should confer some speedup

**Comment by RidwanAlam** [comment] 2021-01-28 18:26
Does that mean, if we find this happening a lot, we have redo the xref generation code? And then tensorize again?

**Comment by RogerPallares** [comment] 2021-01-28 18:28
> can we change the `.mat` conversion process to instead save the start and end time of each bundle? that way, if a bundle overlaps a transfer in/out time, we only have to open that 1 `.mat` file which should confer some speedup

That would be amazing.

**Comment by StevenSong** [comment] 2021-01-28 18:29
> can we change the `.mat` conversion process to instead save the start and end time of each bundle? that way, if a bundle overlaps a transfer in/out time, we only have to open that 1 `.mat` file which should confer some speedup

you know i suppose its actually also possible to just inspect the last timestamp within a `.mat`, just taking the last index of an array from a `.mat` file should be fast?

**Comment by RogerPallares** [comment] 2021-01-28 18:30
> > can we change the `.mat` conversion process to instead save the start and end time of each bundle? that way, if a bundle overlaps a transfer in/out time, we only have to open that 1 `.mat` file which should confer some speedup
> 
> you know i suppose its actually also possible to just inspect the last timestamp within a `.mat`, just taking the last index of an array from a `.mat` file should be fast?

Here comes another question, that I think @epalto can answer: All signals (waveforms and vital signs) finish at the same time? if not we would have to iterate over all of them and find the signal that ends the last.

**Comment by StevenSong** [comment] 2021-01-28 18:31
> > > can we change the `.mat` conversion process to instead save the start and end time of each bundle? that way, if a bundle overlaps a transfer in/out time, we only have to open that 1 `.mat` file which should confer some speedup
> > 
> > 
> > you know i suppose its actually also possible to just inspect the last timestamp within a `.mat`, just taking the last index of an array from a `.mat` file should be fast?
> 
> Here comes another question, that I think @epalto can answer: All signals (waveforms and vital signs) finish at the same time? if not we would have to iterate over all of them and find the signal that ends the last.

I'm pretty sure no, but even so, checking the last element for < 100 signals will be not too slow

**Comment by RidwanAlam** [comment] 2021-01-28 18:33
Before we digress a lot, quick question: 
are the all the hd5 files that we already tensorized have the risk of having multiple patients data in one patient's file? (the patients who were in the same bundle sprint)

**Comment by StevenSong** [comment] 2021-01-28 18:34
> Before we digress a lot, quick question:
> are the all the hd5 files that we already tensorized have the risk of having multiple patients data in one patient's file? (the patients who were in the same bundle sprint)

yes, that's why we ought to quantify how many are actually affected - I did find 1 or 2 patients who were not affected so we shouldnt assume all are bad

**Comment by RidwanAlam** [comment] 2021-01-28 18:36
Of course! The irony is, we have the 'tensorization' concept as a scalable feature that we can rely on blindly to scale across millions of patients, and not looking at each patient to find out whether there is an issue! :((

**Comment by epalto** [comment] 2021-01-28 18:37
>  think @epalto can answer: All signals (waveforms and vital signs) finish at the same time? if not we would have to iterate over all of them and find the signal that ends the last.

Yes, not all of them finish at the same time, but as @StevenSong said, it should be fast to iterate over all signals.

**Comment by StevenSong** [comment] 2021-01-28 18:45
> can we change the `.mat` conversion process to instead save the start and end time of each bundle? that way, if a bundle overlaps a transfer in/out time, we only have to open that 1 `.mat` file which should confer some speedup

another reason for this is that we might actually miss signals by only looking at the start time of the bundles

e.g.

patient A transferred in 1/1 and transferred out 1/2
patient B transferred in 1/2 and transferred out 1/3
patient A and patient B are bundled together and the start of the bundles (the time on each `.mat` filename) is 1/1, however there are 2 `.mat` files, the first bundle goes from 1/1 to 1/2 and the second bundle goes from 1/2 to 1/3

if we do not check the start time of the second bundle and only rely on the time in the filename, we'd assume patient B does not have data in these bundles because they were not admitted prior to 1/2. however this is not the case and the second bundle does contain data belonging to patient B.

**Comment by RogerPallares** [comment] 2021-01-28 18:47
> > can we change the `.mat` conversion process to instead save the start and end time of each bundle? that way, if a bundle overlaps a transfer in/out time, we only have to open that 1 `.mat` file which should confer some speedup
> 
> another reason for this is that we might actually miss signals by only looking at the start time of the bundles
> 
> e.g.
> 
> patient A transferred in 1/1 and transferred out 1/2
> patient B transferred in 1/2 and transferred out 1/3
> patient A and patient B are bundled together and the start of the bundles (the time on each `.mat` filename) is 1/1, however there are 2 `.mat` files, the first bundle goes from 1/1 to 1/2 and the second bundle goes from 1/2 to 1/3
> 
> if we do not check the start time of the second bundle and only rely on the time in the filename, we'd assume patient B does not have data in these bundles because they were not admitted prior to 1/2. however this is not the case and the second bundle does contain data belonging to patient B.

Yes exactly, we'll have more data that now we have "hidden" inside .mat files.

**Comment by RidwanAlam** [comment] 2021-01-28 18:54
@StevenSong and @RogerPallares  what i am hearing, please correct me if i am wrong, is that step 1 is not required then? as any hd5 file, even if there is no time-leap backwards, can contain multiple patient data, right?

**Comment by RidwanAlam** [comment] 2021-01-28 18:55
also, the conclusion is that the issue is in the xref generation, not in the .mat files or before, do you agree?

**Comment by StevenSong** [comment] 2021-01-28 19:13
i think its very likely there are still patients with good data but it is a more complex question to check now - i'm going to close this issue though as the source of the bug has been found and will open new issues for:
1. enhancing tensorizer to take into account these edge cases (#1265)
2. request the `.mat` files be renamed to include the start/end times of the individual bundle

**Comment by RidwanAlam** [comment] 2021-01-28 19:15
> 
> 2. request the `.mat` files be renamed to include the start/end times of the individual bundle

will that need to be done by @matt-cdac and @contactadityag?

**Comment by RidwanAlam** [comment] 2021-02-02 15:03
> Okay, this is really really weird. First of all I checked if this could be a problem of the matching algorithm. For what I checked it doesn't seem so if we consider our ADT as ground truth: The ADT we are using it only has this patient in which the file `LUN06_620-1586396113_38_v4.mat` initial time falls within the patient's Transfer in and Transfer out of LUN0620. Then, if we compare `LUN06_620-1586396113_38_v4.mat` initial time with ADT, it looks like correct, it's like 3 hours after the patient enters to the bed in LUN06. However, this patient is transferred out much before the `LUN06_620-1586396113_38_v4.mat` finishes. Then I have two thoughts:
> 
> 1. Our ADT is not accurate enough and we have patients missing so another could match with this file (`LUN06_620-1586396113_38_v4.mat`). I don't think this is the case though, because it would also mean that 2 patients would be at the same bed at the same time. (not exactly the same but they would be overlapped)
> 2. Somebody in the hospital forgot to turn down the monitors and the next patient that was monitored was recorded with the same file, so some bundles are from one patient, other bundles from another.

2. This is not the case, the signal is continuous, no break at all. Maybe others can look into it just for reinforcement. 
Thanks.

**Comment by erikr** [comment] 2021-02-02 15:08
Ridwan, thanks for digging into this. What are next steps? Perhaps we should quantify this in more detail?

**Comment by RidwanAlam** [comment] 2021-02-02 15:11
@erikr 
> Ridwan, you compared time stamp of a transition (eg new admission, or discharge, or transfer) in the ADT table vs the MAT file, eg patient discharged at 09:22, but there was no interruption in the ECG signal at that time?

Yes ... so the ADT says `Transfer Out` at `4/12/2020 23:25` but the MAT file has no interruption at that point or a little before.

**Comment by RidwanAlam** [comment] 2021-02-02 15:13
> Ridwan, thanks for digging into this. What are next steps? Perhaps we should quantify this in more detail?

I think that has to be done now; for some reason I am failing to see something obvious. 
I will try to quantify this today. @StevenSong @raimonpv and @RogerPallares Please let me know if you have any suggestions.
Thanks.

**Comment by RogerPallares** [comment] 2021-02-02 16:24
Hey @RidwanAlam, thanks for looking at this. I was checking what you said and I think you didn't get the right bundles, actually the Bedmaster files you are considering are not during the transition of the patient from `LUN06` to `BLK08`, could it be you didn't consider that Bedmaster timestamps are in UTC and ADT transfer times in local time? In any case, I checked the file in which the transfer of the patient occurs (`LUN06_620-1586396113_7_v4.mat`), and as you can see in the `HR` plot, there is a huge discontinuity, so I think that my hypothesis is still valid. 

![Captura](https://user-images.githubusercontent.com/52486315/106629369-c27db100-6548-11eb-9f31-f24cd8bcd7fc.PNG)

In any case, thanks for taking a look, it is always appreciated to look into things carefully!

**Comment by RogerPallares** [comment] 2021-02-02 16:29
If you guys agree that the discontinuity really exists, I think we can close the issue again.

**Comment by RidwanAlam** [comment] 2021-02-02 16:46
> Hey @RidwanAlam, thanks for looking into this. I was checking what you said and I think you didn't get the right bundles, actually the Bedmaster files you are considering are not during the transition of the patient from `LUN06` to `BLK08`, could it be you didn't consider that Bedmaster timestamps are in UTC and ADT transfer times in local time? In any case, I checked the file in which the transfer of the patient occurs (`LUN06_620-1586396113_7_v4.mat`), and as you can see in the `HR` plot, there is a huge discontinuity, so I think that the hypothesis that two patients lie on the same Bedmaster files is still valid.
> 
> ![Captura](https://user-images.githubusercontent.com/52486315/106629369-c27db100-6548-11eb-9f31-f24cd8bcd7fc.PNG)
> 
> In any case, thanks for taking a look, it is always appreciated to dig into this kind of things carefully!

I was looking into the timezone thing, exactly. Thanks @RogerPallares

**Comment by RidwanAlam** [comment] 2021-02-02 16:48
Yes, the discontinuity exists. I agree. Thanks for confirming that the ADT is in local time. Appreciate it.

**Comment by RidwanAlam** [comment] 2021-02-02 16:50
Wait, I was using the UTC format from the xref file. Is that one correct? Maybe a new issue?

**Comment by RogerPallares** [comment] 2021-02-02 16:54
Can you clarify what do you see wrong in the xref file transfer times? They look good to me, but maybe there's something I'm not seeing.

**Comment by RidwanAlam** [comment] 2021-02-02 16:55
> Can you clarify what you see wrong in the xref file transfer times? They look good to me, but maybe there's something I'm not seeing.

Yup, that's it.
The `xref` table says `TransferOut` time `1586748300`. Your plot says ~`158685000`.

**Comment by RidwanAlam** [comment] 2021-02-02 17:08
Quick update: the `xref` time matches `adt` time. Maybe the issue is with MAT files timestamps/timezones.

**Comment by RogerPallares** [comment] 2021-02-02 17:17
Okay, so this is a very very strange case I had never found before. It looks like in the ADT, the stay of the patient in LUN06 (same room same bed), is split into 2 different transfers. Look into it carefully, you'll see that this patient is transferred to LUN06 twice: 
- TransferIn 2020-05-08 21:27:00, TransferOut 2020-05-12 23:25:00
- TransferIn 2020-05-12 23:25:00, TransferOut 2020-05-14 04:37:00
The  issue here is that our code to match patients with Bedmaster files only takes the start time and compares it to the TransferIn and TransferOut, therefore, all Bedmaster files lie in the first transfer, and this is why you are seeing the times from the first transfer in the xref table and not the second ones. This issue is solved with @StevenSong and @raimonpv improvements on taking initial and end times from Bedmaster files and updating the matching algorithm accordingly.

**Comment by RidwanAlam** [comment] 2021-02-02 17:32
Cool!!. Yeah, that makes sense. I believe you typed May instead of April.
So maybe we should now look at the `B0854 A` data, why it starts earlier than `4/14/2020  4:37:00 AM`?

**Comment by RogerPallares** [comment] 2021-02-02 17:35
Yes, I meant April, it was a typo. Where do you see it starts earlier? Can you put the timestamps?

**Comment by RidwanAlam** [comment] 2021-02-02 17:44
no no, the mat files, as shown in the figure at the very top.

**Comment by RidwanAlam** [comment] 2021-02-02 17:47
Nvm, you're right. I was thinking about the backward time jump in the plot at the very top of this page.

**Comment by RogerPallares** [comment] 2021-02-02 17:47
Bedmaster files from `B0854 `start at `1586853541`, which in local times tamp is: 2020-04-14 03:39:00, more or less 1 hour before the patient was transferred. This is right, as they prepare the monitors before the patients come to the bed.

**Comment by RidwanAlam** [comment] 2021-02-02 17:50
So ... on the plot above, the first slope needs to be filtered out as it belongs to another patient, right?

**Comment by RogerPallares** [comment] 2021-02-02 17:55
Not all the first slope, the part before `B0854 `bedmaster file starts is from the same patient and must be kept.

**Closed** 2021-02-02 18:11 UTC
Labels: bug 🐛

**Comment by erikr** [comment] 2021-02-04 02:42
> patient A transferred in 1/1 and transferred out 1/2
> patient B transferred in 1/2 and transferred out 1/3
> patient A and patient B are bundled together and the start of the bundles (the time on each `.mat` filename) is 1/1, however there are 2 `.mat` files, the first bundle goes from 1/1 to 1/2 and the second bundle goes from 1/2 to 1/3

@StevenSong, why do both bundles have a start time of 1/1?

**Comment by RidwanAlam** [comment] 2021-02-04 04:25
> > patient A transferred in 1/1 and transferred out 1/2
> > patient B transferred in 1/2 and transferred out 1/3
> > patient A and patient B are bundled together and the start of the bundles (the time on each `.mat` filename) is 1/1, however there are 2 `.mat` files, the first bundle goes from 1/1 to 1/2 and the second bundle goes from 1/2 to 1/3
> 
> @StevenSong, why do both bundles have a start time of 1/1?

@erikr are you asking why same start time on mat file name? that's the way the mat files are named, all bundles from one session (when the machine was turned on to shut down). not in our hands.
if you are asking why same t_start in bedmaster_index.csv file, that shouldn't be the case; we need to look into this.

**Comment by RidwanAlam** [comment] 2021-02-04 05:34
> @RidwanAlam if you agree step 1 is helpful here, do you have bandwidth to help with that?

https://github.com/aguirre-lab/ml4c3/pull/1293#issuecomment-773034685

**Comment by erikr** [comment] 2021-02-04 14:29
Ah, I remember now. If you have >1 bundle, they are named:
```
BLK08_26-1111111111_0_v4.mat
BLK08_26-1111111111_1_v4.mat
BLK08_26-1111111111_2_v4.mat
```
where `1111111111` is the start time.

The `t_start` in `bedmaster_index.csv` is not identical. That differs for each entry.
