### ISSUE TITLE
Enhance tensorization to split .mat bundles

### ISSUE THREAD

**Issue by StevenSong** [aguirre-lab/ml4c3#1265] opened 2021-01-28 18:39 UTC
## What and why
#1258 has shown us that we cannot assume 1:1 relationship between `.mat` file and patient. So tensorizer needs to be able to split up a `.mat` file 

## Solution(s)
algorithm might be:
1. check the end time of a `.mat` file
1. if it overlaps a transfer in/out time, only take values from after/before the overlap

## Acceptance criteria
hd5 files only contain data from 1 patient

**Comment by StevenSong** [comment] 2021-01-28 19:00
we need to modify:
- the cross referencer to include any `.mat` for which the patient might have data
- the bedmaster reader to only extract those signals belonging to the patient

**Comment by erikr** [comment] 2021-01-28 20:01
@StevenSong As you craft an implementation, I think it would be prudent to assume the CDAC team cannot complete https://github.com/aguirre-lab/ml4c3/issues/1265 in a timely manner. They, like most teams, have more tasks than capacity. Given we have not quantified the problem, it will be difficult to convince Brandon to have his team work on it.

**Comment by erikr** [comment] 2021-01-28 20:01
@RidwanAlam on that note, how difficult would it be to quantify this problem, at least to an order of magnitude?

**Comment by erikr** [comment] 2021-01-28 21:29
Hey @matt-cdac @contactadityag, I just spoke w/ Aaron, Brandon, and @StevenSong about this.

Brandon agrees this problem must be addressed in order for your team to ship your data deliverable. However, he said you lack bandwidth to tackle this now.

We'll implement a fix here. You can review our PR and implement whatever you find helpful in your fork. But eventually you will need to modify your fork to address this issue.

**Comment by RidwanAlam** [comment] 2021-01-29 03:10
> @RidwanAlam on that note, how difficult would it be to quantify this problem, at least to an order of magnitude?

@erikr sorry missed the comm. Honestly, not sure how to even quantify this issue. The only way to quantify is the same as the solution @StevenSong proposed, redo-ing the xref-like big table that will identify the mat files with overlapping patient info. Please correct me if I am missing another view. Thanks.

**Comment by erikr** [comment] 2021-01-29 03:22
Makes sense. The solution to the cause of this problem requires creating a `xref` table (via iterating over every patient and encounter). Once we have the table, it should be trivial to quantify the problem. But I also do not see a way to quantify the problem a priori.

**Comment by RidwanAlam** [comment] 2021-02-04 05:37
> @RidwanAlam on that note, how difficult would it be to quantify this problem, at least to an order of magnitude?

https://github.com/aguirre-lab/ml4c3/pull/1293#issuecomment-773034685

**Comment by StevenSong** [comment] 2021-02-04 16:44
still need to modify the writer

**Comment by raimonpv** [comment] 2021-02-04 16:46
Sorry, don't know why the PR close it as I didn't linked it

**Closed** 2021-02-09 17:46 UTC
Labels: infrastructure 🚇
