### ISSUE TITLE
bedmaster_index.csv incorrect t_start and/or t_end

### ISSUE THREAD

**Issue by RidwanAlam** [aguirre-lab/ml4c3#1304] opened 2021-02-04 04:37 UTC
In the `bedmaster_index.csv` file, there are 1,278,382 indices for `.mat` files.

1. in some (<100) cases, `t_start` is <=0: should we ignore those files? Which waveform/vital's time vector was being checked to get the `t_start`? Is it possible, that parameter was missing in those files?

2. when looking for reasonable file durations, i.e. for `t_delta = t_end - t_start`, finding the index of problematic timestamps `np.where(t_delta<60 | t_delta>600000)` gives 30,215 indices. that means a lot of files have less than a minute's worth data (?!) or something wrong with the timestamp. Again, which waveform/vital's time vector was being checked to get the `t_start`? Is it possible, that parameter was rare in those files?

**Comment by StevenSong** [comment] 2021-02-04 14:39
> 1. in some (<100) cases, `t_start` is <=0: should we ignore those files? Which waveform/vital's time vector was being checked to get the `t_start`? Is it possible, that parameter was missing in those files?

it checks all waveforms and vitals for the first element of their time vectors. it takes whatever is the smallest. if one of them happens to have `-1` as the first element in `t_start`, the algorithm takes `-1`. I'll add a special case for this

> 2\. when looking for reasonable file durations, i.e. for `t_delta = t_end - t_start`, finding the index of problematic timestamps `np.where(t_delta<60 | t_delta>600000)` gives 30,215 indices. that means a lot of files have less than a minute's worth data (?!) or something wrong with the timestamp. Again, which waveform/vital's time vector was being checked to get the `t_start`? Is it possible, that parameter was rare in those files?

bundles greater than 10,000 hours are probably because of `t_start = -1` - those will be fixed with the special case. bundle durations less than a minute are odd, will look into

**Comment by RidwanAlam** [comment] 2021-02-04 14:52
> bundle durations less than a minute are odd, will look into

that number is high, ~30K.

**Comment by StevenSong** [comment] 2021-02-04 14:54
point taken its a big count but I do only see 15K are `t_delta < 60`?

**Comment by RidwanAlam** [comment] 2021-02-04 14:59
that's correct.

**Comment by RidwanAlam** [comment] 2021-02-04 15:01
so .. are the files with `t_delta>600000` wrong? should we ignore those, or still use it? what would be the upper threshold for skipping?

**Comment by StevenSong** [comment] 2021-02-04 15:04
> so .. are the files with `t_delta>600000` wrong? should we ignore those, or still use it? what would be the upper threshold for skipping?

https://github.com/aguirre-lab/ml4c3/wiki/Bedmaster-raw-data#structure

given bundles should only be at most 1100 minutes, `t_delta > 66,000` (maybe also some buffer, `70,000` minutes?) are wrong

@epalto thoughts?

**Comment by StevenSong** [comment] 2021-02-04 15:12
`t_delta < 60` seems to be correct though, take for example `BLK08/BLK08_854-1448485806_0_v4.mat`. inspecting the `.mat` file, `t_delta = 3 seconds`. Admittedly, my understanding of how to inspect the `.mat` file is the same logic I use in the indexer so please double check that file. If you agree, I don't think there's anything necessarily wrong with `t_delta < 60`

**Comment by RidwanAlam** [comment] 2021-02-04 15:56
agree, it's just a bit confusing :(

**Comment by epalto** [comment] 2021-02-04 15:56
I think that `t_delta > 60` may happen on `.mat` files because of the overlapped section. I don't know exactly how this overlap is generated but some files only contain the overlapped part from the previous file, i.e. only contain redundant information. I suppose that if a `.mat` file contains: 100 overlap with previous + 901 minutes of data, the next `.mat` file is automatically generated with this 1 minute of overlapping information with the previous file, creating a new `.mat` file that only contains 1 min of information. I have not confirmed this explanation but I can confirm that during tensorization a lot of files are ignored because they only contain overlapping (redundant) information, so that may explain `tdelta<60`. 

`t_delta > 66,000` sounds too much, but as you said @StevenSong , could it be because it takes `start_time=-1`?

**Comment by RidwanAlam** [comment] 2021-02-04 16:00
> I think that `t_delta > 60` may happen on `.mat` files because of the overlapped section. I don't know exactly how this overlap is generated but some files only contain the overlapped part from the previous file, i.e. only contain redundant information. I suppose that if a `.mat` file contains: 100 min of overlap with previous + 901 minutes of new data, the next `.mat` file is automatically generated with this 1 minute of overlapping information with the previous file, creating a new `.mat` file that only contains 1 min of information. I have not confirmed this explanation but I can confirm that during tensorization a lot of files are ignored because they only contain overlapping (redundant) information, so that may explain `tdelta<60`.
> 
> `t_delta > 66,000` sounds too much, but as you said @StevenSong , could it be because it takes `start_time=-1`?

@epalto `t_delta>60` refers to 60 seconds, sorry for the confusion

**Comment by RidwanAlam** [comment] 2021-02-04 16:03
I agree, we can leave those files with `t_delta<60 (seconds)` for now, since the `tensorizer` will take care of those.
But for the large files, `t_delta>600,000 (seconds)`, we should keep those as well unless `t_start` was -1?

**Comment by StevenSong** [comment] 2021-02-04 16:06
> I agree, we can leave those files with `t_delta<60 (seconds)` for now, since the `tensorizer` will take care of those.
> But for the large files, `t_delta>600,000 (seconds)`, we should keep those as well unless `t_start` was -1?

`t_start < 0` will be fixed soon, I updated some code and am rerunning the index on those files

I'm also investigating occurrences where `t_delta > 70,000 seconds` and `t_start > 0`, as that is a stranger case

**Comment by epalto** [comment] 2021-02-04 16:06
> I think that `t_delta > 60` may happen on .mat...

Sorry, I meant `t_delta < 60`

**Comment by StevenSong** [comment] 2021-02-04 16:30
> I'm also investigating occurrences where `t_delta > 70,000 seconds` and `t_start > 0`, as that is a stranger case

this latter case is a symptom of #1307. we can't simply go by 70,000 seconds and additionally i dont think any heuristic is appropriate as this adds another assumption. so files where `t_delta > 70,000 seconds` I'd say are still usable.

**Closed** 2021-02-04 22:13 UTC
Labels: bug 🐛
